// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpJTvFG0edwIKOv9xlzI8N0M27nlEZ6lA',
    appId: '1:387530988784:web:09eaa7698ccbf6ad3b7635',
    messagingSenderId: '387530988784',
    projectId: 'test-4a43c',
    authDomain: 'test-4a43c.firebaseapp.com',
    storageBucket: 'test-4a43c.firebasestorage.app',
    measurementId: 'G-QD0B4W2M27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPx4d4bNRpOVeSTBJztKN-rZB0dhdMYS0',
    appId: '1:387530988784:android:05917bbd64eb1a173b7635',
    messagingSenderId: '387530988784',
    projectId: 'test-4a43c',
    storageBucket: 'test-4a43c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNr_JtuhRiow5rMQFyTKpe26iTOp1mG5c',
    appId: '1:387530988784:ios:4b0cae585d4556723b7635',
    messagingSenderId: '387530988784',
    projectId: 'test-4a43c',
    storageBucket: 'test-4a43c.firebasestorage.app',
    iosBundleId: 'com.example.feedbackCollectorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNr_JtuhRiow5rMQFyTKpe26iTOp1mG5c',
    appId: '1:387530988784:ios:4b0cae585d4556723b7635',
    messagingSenderId: '387530988784',
    projectId: 'test-4a43c',
    storageBucket: 'test-4a43c.firebasestorage.app',
    iosBundleId: 'com.example.feedbackCollectorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpJTvFG0edwIKOv9xlzI8N0M27nlEZ6lA',
    appId: '1:387530988784:web:0dc24b7a387478b53b7635',
    messagingSenderId: '387530988784',
    projectId: 'test-4a43c',
    authDomain: 'test-4a43c.firebaseapp.com',
    storageBucket: 'test-4a43c.firebasestorage.app',
    measurementId: 'G-6WKJGXPJBN',
  );
}
